version: '2'

services:
  db:
    image: postgres
    container_name: hardcontrol_db_1
    ports:
      - "5432:5432"
  web:
    build: .
    command: python3 manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    container_name: hardcontrol_1
    ports:
      - "8000:8000"
    depends_on:
      - db
