# Generated by Django 2.0.6 on 2018-06-06 12:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hardcontrol', '0002_hard_objects_rfid_id'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Hard_objects',
        ),
    ]
