# Generated by Django 2.0.6 on 2018-07-04 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hardcontrol', '0006_auto_20180629_1008'),
    ]

    operations = [
        migrations.AddField(
            model_name='hard_objects',
            name='name',
            field=models.CharField(default='', max_length=1000, verbose_name='Наименование инженерно-технического средства'),
        ),
        migrations.AddField(
            model_name='hard_objects',
            name='name_rem',
            field=models.CharField(default='', max_length=1000, verbose_name='Наименование ремонтных комплектов'),
        ),
        migrations.AddField(
            model_name='hard_objects',
            name='number1',
            field=models.CharField(default='', max_length=1000, verbose_name='Инвентарный (заводской) номер средства связи'),
        ),
        migrations.AddField(
            model_name='hard_objects',
            name='number2',
            field=models.CharField(default='', max_length=1000, verbose_name='Инвентарный (заводской) номер инженерно-технического средства'),
        ),
        migrations.AddField(
            model_name='hard_objects',
            name='number_name',
            field=models.CharField(default='', max_length=1000, verbose_name='Марка транспортного средства'),
        ),
        migrations.AddField(
            model_name='hard_objects',
            name='number_reg',
            field=models.CharField(default='', max_length=1000, verbose_name='Номер свидетельства о регистрации'),
        ),
    ]
