# Generated by Django 2.0.6 on 2018-07-04 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hardcontrol', '0009_hard_objects_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='fio',
            field=models.CharField(blank=True, default='', max_length=1000, verbose_name='Фамилия Имя Отчество'),
        ),
    ]
