# Generated by Django 2.0.6 on 2018-07-05 13:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hardcontrol', '0012_hardonworker_hardtransaction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hardonworker',
            name='hard_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hardcontrol.Hard_objects'),
        ),
        migrations.AlterField(
            model_name='hardonworker',
            name='worker_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='hardtransaction',
            name='hard_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hardcontrol.Hard_objects'),
        ),
        migrations.AlterField(
            model_name='hardtransaction',
            name='worker_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
