# Generated by Django 2.0.6 on 2018-07-10 13:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('hardcontrol', '0013_auto_20180705_1312'),
    ]

    operations = [
        migrations.AddField(
            model_name='hardonworker',
            name='manager_id',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, related_name='h_manager_id', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='hardtransaction',
            name='manager_id',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, related_name='t_manager_id', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='hardonworker',
            name='worker_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='h_worker_id', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='hardtransaction',
            name='worker_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='t_worker_id', to=settings.AUTH_USER_MODEL),
        ),
    ]
