# Generated by Django 2.0.6 on 2018-07-30 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hardcontrol', '0015_hard_objects_repair'),
    ]

    operations = [
        migrations.AddField(
            model_name='hard_objects',
            name='comlect',
            field=models.TextField(blank=True, verbose_name='Комплектность оборудования'),
        ),
        migrations.AlterField(
            model_name='hard_objects',
            name='number1',
            field=models.CharField(blank=True, default='', max_length=1000, verbose_name='Инвентарный номер'),
        ),
        migrations.AlterField(
            model_name='hard_objects',
            name='number2',
            field=models.CharField(blank=True, default='', max_length=1000, verbose_name='Заводской номер'),
        ),
    ]
