# Generated by Django 2.0.6 on 2018-07-30 11:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hardcontrol', '0016_auto_20180730_1233'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hard_objects',
            old_name='comlect',
            new_name='complect',
        ),
    ]
