# Generated by Django 2.0.6 on 2018-08-30 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hardcontrol', '0017_auto_20180730_1413'),
    ]

    operations = [
        migrations.AddField(
            model_name='hard_objects',
            name='dop_1',
            field=models.CharField(blank=True, default='', max_length=1000, verbose_name='№ паспорта'),
        ),
        migrations.AddField(
            model_name='hard_objects',
            name='dop_2',
            field=models.CharField(blank=True, default='', max_length=1000, verbose_name='№ удостоверения'),
        ),
        migrations.AddField(
            model_name='hard_objects',
            name='dop_3',
            field=models.CharField(blank=True, default='', max_length=1000, verbose_name='Денежные средства'),
        ),
        migrations.AddField(
            model_name='hard_objects',
            name='dop_4',
            field=models.CharField(blank=True, default='', max_length=1000, verbose_name='Вид и номер носильных МТС.'),
        ),
    ]
