# Generated by Django 2.0.7 on 2018-08-31 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hardcontrol', '0018_auto_20180830_1240'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='face_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='hard_objects',
            name='dop_4',
            field=models.CharField(blank=True, default='', max_length=1000, verbose_name='Вид и номер носильных МТС'),
        ),
    ]
